//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> OrderDetailID { get; set; }
        public string BankName { get; set; }
        public string BankNumber { get; set; }
        public string PaymentBank { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<double> Payment1 { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
    }
}
